### PR TITLE
A wrapper around MediaStore.Audio ( only SELECT Queries on music files)

### PR DESCRIPTION
**Pull request by Drazail**
- custom folder path for covers - to prevent interference with other images and easier clean up
- cover resize -  this can help the performance with large lists
- icons - generating icons from the cover images to improve performance
- custom size for icons and cover - as image manipulation is extremely expensive on the js thread, reducing the dimensions to a fixed number can improve performance.

### CODE REVIEW

**Comment by cinder92** [comment]
Hello, thanks for your pr, have you test this changes on Android lower versions? Like KitKat?

**Comment by Drazail** [comment]
Our app does not supporting versions < 5.0, however I can take a look and run some tests as soon as possible.

**Comment by Drazail** [comment]
@cinder92 could you please take a look at [this](https://github.com/Drazail/react-native-get-music-files/tree/development) and let me know if you are interested in merging any of the other added features so I can test them on KitKat all at once?

You can find the generated documentation in the "out"  folder.

**Comment by cinder92** [comment]
@Drazail sorry for late response, did you have change to test it? at least in android 5 and above?

**Comment by cinder92** [comment]
@Drazail did you test this changes on iOS aswell?

**Comment by Drazail** [comment]
@cinder92 

I moved all the newly added features of this pullRequest to RNAndroidAudioStore, ie :
```JavaScript 
import MusicFiles, { RNAndroidAudioStore } from "react-native-get-music-files";
```
MusicFiles is still the default export and is untouched.

A new Class called RNAndroidAudioStore is implemented and should be imported separately in MainApplication.java ( if the functionality is need of course):
```Java
import com.drazail.rnandroidstore.RNAndroidStorePackage;
```

```Java
new RNAndroidStorePackage()
```
RNAndroidAudioStore is only compatible with android 5+, doesn't support iOS and implements following methods:

- getAll
- getAlbums
- getArtists
- getSongByPath
- getSongs
- getSongsByGenres
- search

I published the first version of documentations [here](https://drazail.github.io/index.html).
[example app](https://github.com/Drazail/react-native-get-music-files/tree/development/example)

**Comment by cinder92** [comment]
@Drazail  perfect, i don't test it yet, but while main package works its ok, PR accepted

**Comment by cinder92** [comment]
@Drazail could you please make a PR for Update the README ? thanks

**Comment by Drazail** [comment]
@cinder92, sure, will do it asap, meanwhile you can find the documentation on my GitHub page: https://drazail.github.io/index.html

**Pull request merged**
