### PR TITLE
[v2.2] - Turbo module (iOS & Android)

### PR DESCRIPTION
**Pull request by cinder92**
- [x] Compatible with RN 0.7+
- [x] Compatible with iOS & Android
- [x] Limit & offset to improve speed
- [x] Removed blur and other properties
- [x] NO more event handlers
- [x] Permission need to be handled by your own
- [x] getAll, getAlbums, searchSongs method works for iOs & Android 

@Drazail could you help to test? thanks

## Tested on
- [x] Real iPhone 13 iOs 16.6.1
- [x] Android 11 & 13 

## How to install
https://stackoverflow.com/questions/33181297/npm-install-from-github-pull-request

### CODE REVIEW

**Comment by cinder92** [comment]
@flarocca @Haggaish @anthonytietjen @krishcdbry when you have time, please help testing :)

**Comment by adey69** [comment]
On Android 14, even after granting `READ_MEDIA_AUDIO` permission, the `getAll` function returns an error "Permission denied". I can see the permission being allowed in the settings of the phone. Might want to check this out.

**Comment by dante-cervantes-rocketlab** [comment]
> On Android 14, even after granting `READ_MEDIA_AUDIO` permission, the `getAll` function returns an error "Permission denied". I can see the permission being allowed in the settings of the phone. Might want to check this out.

hi @adey69, have you tried requesting `READ_EXTERNAL_STORAGE` instead?

**Comment by adey69** [comment]
> > On Android 14, even after granting `READ_MEDIA_AUDIO` permission, the `getAll` function returns an error "Permission denied". I can see the permission being allowed in the settings of the phone. Might want to check this out.
> 
> hi @adey69, have you tried requesting `READ_EXTERNAL_STORAGE` instead?

Hi @dante-cervantes-rocketlab, I did try it first but then changed it to `READ_MEDIA_AUDIO`. Refer to the following:
https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

**Comment by dante-cervantes-rocketlab** [comment]
> > > On Android 14, even after granting `READ_MEDIA_AUDIO` permission, the `getAll` function returns an error "Permission denied". I can see the permission being allowed in the settings of the phone. Might want to check this out.
> > 
> > 
> > hi @adey69, have you tried requesting `READ_EXTERNAL_STORAGE` instead?
> 
> Hi @dante-cervantes-rocketlab, I did try it first but then changed it to `READ_MEDIA_AUDIO`. Refer to the following: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

Can you create a minimal reproduction of the issue and details of the device? last time i updated the code was tested on Android 13, probably i can test on Android 14 in a simulator ...

**Comment by adey69** [comment]
> > > > On Android 14, even after granting `READ_MEDIA_AUDIO` permission, the `getAll` function returns an error "Permission denied". I can see the permission being allowed in the settings of the phone. Might want to check this out.
> > > 
> > > 
> > > hi @adey69, have you tried requesting `READ_EXTERNAL_STORAGE` instead?
> > 
> > 
> > Hi @dante-cervantes-rocketlab, I did try it first but then changed it to `READ_MEDIA_AUDIO`. Refer to the following: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions
> 
> Can you create a minimal reproduction of the issue and details of the device? last time i updated the code was tested on Android 13, probably i can test on Android 14 in a simulator ...

Here you go for the minimal code. It's based on the example provided by the package owner.
Device information:
Samsung Galaxy S23 Ultra
OS: Android 14
https://github.com/adey69/music_player_test

**Comment by cinder92** [comment]
hi @adey69 i have pushed an update in the `master` branch that fixes the issue for android 14, please take a look.

**Comment by adey69** [comment]
> hi @adey69 i have pushed an update in the `master` branch that fixes the issue for android 14, please take a look.

Hi @cinder92, working fine now. Thanks for the quick response.

**Pull request merged**
