### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by nguyenkhooi**
Request created based on @YajanaRao 's fork:

Update `s.homepage` to `s.homepage = "https://github.com/cinder92/react-native-get-music-files"` fix installing pod issue:

```
 The `RNReactNativeGetMusicFiles` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.
```

### CODE REVIEW

**Comment by cinder92** [comment]
@Drazail are you ok to be removing main code?

**Comment by Drazail** [comment]
> @Drazail are you ok to be removing main code?

is it possible to link the part of code you refer to please?

**Comment by codal-mpawar** [comment]
working for me please merge so we can pull

**Review by codal-mpawar — APPROVED** [review]

**Comment by cinder92** [comment]
@nguyenkhooi there are some issues could you please test it?

**Comment by cinder92** [comment]
closing this in favor of https://github.com/cinder92/react-native-get-music-files/pull/108

**Pull request closed without merging**
